name: Garmin Weekly Report
on:
  schedule:
    # 19:00 UTC every Sunday
    - cron:  '0 19 * * SUN'
  workflow_dispatch:  # allow manual runs too

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    env:
      # these secrets you must add under your repo Settings
      GMAIL_EMAIL:        ${{ secrets.GMAIL_EMAIL }}
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      GARMINCONNECT_MAIL:   ${{ secrets.GARMINCONNECT_MAIL }}
      GARMINCONNECT_PASSWORD: ${{secrets.GARMINCONNECT_PASSWORD}}
      OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
      REPORT_RECIPIENT: ${{secrets.REPORT_RECIPIENT}}
      USER_AGE: ${{secrets.USER_AGE}}
      USER_HEIGHT: ${{secrets.USER_HEIGHT}}
      USER_WEIGHT: ${{secrets.USER_WEIGHT}}
      USER_SEX: ${{secrets.USER_SEX}}
      USER_AMBITIONS: ${{secrets.USER_AMBITIONS}}
      CURRENT_JOB: ${{secrets.CURRENT_JOB}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install uv and dependencies
        run: |
              python -m pip install --upgrade pip
              pip install uv
              uv venv
              uv pip install -e .

      - name: Run weekly report
        run: uv run -m client.garminReport --fetch TRUE

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: garmin-report-html
          path: report/output/report.html
